### PR TITLE
Various updates to module

### PR DESCRIPTION
**Pull request by fatmcgav**
Updated module to include: 
- Pulled out default param values into etcd::params, to add multi-OS support
- EL OS support, including InitD script and sysconfig file
- Add support for etcd Discovery 
- Removed '-max-cluster-size' config, as deprecated
- Various other tweaks and 

Pulled in commits from following forks:
- @intjonathan
- @relistan
- @bobtfish
- @Finchster

Will follow up with further test cases for the EL support.

### CODE REVIEW

**Comment by solarkennedy** [comment]
Wow! What a pull request!

I don't see a travis build for some reason? Can you manually confirm that `bundle exec rake spec` is green?

**Comment by fatmcgav** [comment]
Hehe, it did turn into a bit of a mammoth one... 
I noticed that it didn't trigger a TravisCI build aswell. 

However I did build it in TravisCI on my side: https://travis-ci.org/fatmcgav/puppet-etcd/builds/27880899

Cheers
Gav

**Comment by relistan** [comment]
:+1:

**Comment by intjonathan** [comment]
It's a neatly chiseled, well-groomed, drop-dead handsome pull request!

**Comment by fatmcgav** [comment]
Cheers both... 😊

**Comment by solarkennedy** [comment]
Great! Again, thank you for collecting all this together.

You are now a contributor! No need to fork! You can still do PRs if you want code review.

**Comment by Finchster** [comment]
Awesome! Thanks guys.

**Comment by fatmcgav** [comment]
No worries, and Cheers for adding me as a contributor...

**Pull request merged**
