### PR TITLE
Improve installation in debian

### PR DESCRIPTION
**Pull request by rhoml**
- Adds package_url this way users can create their own deb packages and upload them anywhere puppet will download and install.
- Adds package_version this way they can upgrade etcd.

### CODE REVIEW

**Comment by solarkennedy** [comment]
I'm not sure about the idea of having special code to download _deb_ specific packages in the codebase.

I've never seen any other puppet module that does this, and in general, I consider it outside the scope of puppet to provide a package this way.

Plus it is "deb" specific. Why not do this for every type of package? If uses are going to upload them somewhere they should run "dpkg-scanpackages" so they can add it as a source and install things like normal?

**Comment by rhoml** [comment]
- There are a few recognised modules that allows this elasticsearch, logstash for instance.
- How does this modules spec that the debian package is available? either etcd has a repo that we can add as an APT source or PPA or we need to find a way to distribute the package transparently to puppet.

**Comment by fatmcgav** [comment]
I'm inclined to agree with @solarkennedy. Downloading OS packages is usually best handled by the native package utils.
Downloading source files such as .tar.gz files etc is something that I support having alternative location params for... 

If you want to create a customised package, host it on an internal package repo, and configure the host to use that outside of this module. 

Or at the very minimum, this change should support both RPM and DEB distros... 

Cheers 
Gav

**Comment by rhoml** [comment]
So how do you think is the best way to make the deb package available so you can use the package resource of puppet? 

Generate your etcd deb package with fpm, then what?

**Comment by fatmcgav** [comment]
At work, we're a EL shop, so our RPMs get hosted on a central server, and served out using mrepo and apache for yum to consume.

You can do similar with debs using an apt repo, e.g http://davehall.com.au/blog/dave/2010/02/06/howto-setup-private-package-repository-reprepro-nginx

**Comment by solarkennedy** [comment]
If you have a URL, then you can make a trivial apt repo with dpkg-scanpackages and have a proper repo: 
https://www.debian.org/doc/manuals/repository-howto/repository-howto.en.html#id443677

There are many ways to do it.

**Pull request closed without merging**
