### PR TITLE
Added tests for EL support, plus bug fixes.

### PR DESCRIPTION
**Pull request by fatmcgav**
- Added tests for EL support. 
- Fixed a bug with enabling verbose or very_verbose logging on EL. 
- Fixed a bug with '/etc/etcd/etcd.conf' file ownership on Debian. 
- Added Puppet resource test coverage stats. 
- Switched to using Librarian-Puppet to install module dependencies.

### CODE REVIEW

**Comment by fatmcgav** [comment]
TravisCI passed. 

Will merge this one in later unless anyone objects. 

Gav

**Comment by fatmcgav** [comment]
Will rewrite the commits on this one before I merge it in, as it's got a bit messy :(

**Comment by solarkennedy** [comment]
Looks really comprehensive! Shipit. Afterwards I'll bump the forge release.

**Comment by fatmcgav** [comment]
Ta. New PR incoming with a slightly cleaner history, as there were a lot of 'hiccups' with EOL on this one :(

**Pull request closed without merging**
